version: '3'
services:
  replybot:
    build: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
    env_file: .env
    command: npm run dev
  botserver:
    image: nandanrao/gbv-botserver
    env_file: .env
    ports:
      - "3000:80"
  redis:
    image: redis
